# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

  Deal.create(
    id: 100,
    name: "iPhone 6",
    description: "iPhone 6",
    price: 10,
    image: nil,
    threshold: 2,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQdRq0PxGe1HYR5kcCGZpKGIzGHw5mjBFTJZFLlqeZOobbqNlLvPg",
    product_type: "Electronics",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 101,
    name: "XBOX ONE",
    description: "XBOX ONE",
    price: 10,
    image: nil,
    threshold: 2,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwp4BVJdeXqJsdYFF7YPOhgLBOvET2x16-gxdIsMoDJ1-el2of9A",
    product_type: "Video Games",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 102,
    name: "iPhone 6a",
    description: "iPhone 6",
    price: 10,
    image: nil,
    threshold: 2,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQdRq0PxGe1HYR5kcCGZpKGIzGHw5mjBFTJZFLlqeZOobbqNlLvPg",
    product_type: "Electronics",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 103,
    name: "XBOX ONEa",
    description: "XBOX ONE",
    price: 10,
    image: nil,
    threshold: 2,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwp4BVJdeXqJsdYFF7YPOhgLBOvET2x16-gxdIsMoDJ1-el2of9A",
    product_type: "Video Games",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 104,
    name: "iPhone 6b",
    description: "iPhone 6",
    price: 10,
    image: nil,
    threshold: 2,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQdRq0PxGe1HYR5kcCGZpKGIzGHw5mjBFTJZFLlqeZOobbqNlLvPg",
    product_type: "Electronics",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 105,
    name: "XBOX ONEb",
    description: "XBOX ONE",
    price: 10,
    image: nil,
    threshold: 2,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwp4BVJdeXqJsdYFF7YPOhgLBOvET2x16-gxdIsMoDJ1-el2of9A",
    product_type: "Video Games",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 106,
    name: "iPhone 6c",
    description: "iPhone 6",
    price: 10,
    image: nil,
    threshold: 2,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQdRq0PxGe1HYR5kcCGZpKGIzGHw5mjBFTJZFLlqeZOobbqNlLvPg",
    product_type: "Electronics",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 107,
    name: "XBOX ONEc",
    description: "XBOX ONE",
    price: 10,
    image: nil,
    threshold: 2,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwp4BVJdeXqJsdYFF7YPOhgLBOvET2x16-gxdIsMoDJ1-el2of9A",
    product_type: "Video Games",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 108,
    name: "iPhone 6d",
    description: "iPhone 6",
    price: 10,
    image: nil,
    threshold: 2,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQdRq0PxGe1HYR5kcCGZpKGIzGHw5mjBFTJZFLlqeZOobbqNlLvPg",
    product_type: "Electronics",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

  Deal.create(
    id: 109,
    name: "XBOX ONEd",
    description: "XBOX ONE",
    price: 10,
    image: nil,
    threshold: 2,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwp4BVJdeXqJsdYFF7YPOhgLBOvET2x16-gxdIsMoDJ1-el2of9A",
    product_type: "Video Games",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )


  Deal.create(
    id: 110,
    name: "iPhone 6e",
    description: "iPhone 6",
    price: 10,
    image: nil,
    threshold: 2,
    start_date: nil,
    end_date: nil,
    status: "ready",
    supplier_id: 1,
    created_at: "2015-08-10 20:00:00",
    updated_at: "2015-08-10 21:00:00",
    url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQdRq0PxGe1HYR5kcCGZpKGIzGHw5mjBFTJZFLlqeZOobbqNlLvPg",
    product_type: "Electronics",
    winning_order_id: nil,
    winning_consumer: nil,
    winners_shipping_address: nil,
    threshold_reached: false,
    )

    Deal.create(
      id: 111,
      name: "XBOX ONEe",
      description: "XBOX ONE",
      price: 10,
      image: nil,
      threshold: 2,
      start_date: nil,
      end_date: nil,
      status: "ready",
      supplier_id: 1,
      created_at: "2015-08-10 20:00:00",
      updated_at: "2015-08-10 21:00:00",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwp4BVJdeXqJsdYFF7YPOhgLBOvET2x16-gxdIsMoDJ1-el2of9A",
      product_type: "Video Games",
      winning_order_id: nil,
      winning_consumer: nil,
      winners_shipping_address: nil,
      threshold_reached: false,
      )

    Deal.create(
      id: 112,
      name: "iPhone 6f",
      description: "iPhone 6",
      price: 10,
      image: nil,
      threshold: 2,
      start_date: nil,
      end_date: nil,
      status: "ready",
      supplier_id: 1,
      created_at: "2015-08-10 20:00:00",
      updated_at: "2015-08-10 21:00:00",
      url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQdRq0PxGe1HYR5kcCGZpKGIzGHw5mjBFTJZFLlqeZOobbqNlLvPg",
      product_type: "Electronics",
      winning_order_id: nil,
      winning_consumer: nil,
      winners_shipping_address: nil,
      threshold_reached: false,
      )

    Deal.create(
      id: 113,
      name: "XBOX ONEf",
      description: "XBOX ONE",
      price: 10,
      image: nil,
      threshold: 2,
      start_date: nil,
      end_date: nil,
      status: "ready",
      supplier_id: 1,
      created_at: "2015-08-10 20:00:00",
      updated_at: "2015-08-10 21:00:00",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwp4BVJdeXqJsdYFF7YPOhgLBOvET2x16-gxdIsMoDJ1-el2of9A",
      product_type: "Video Games",
      winning_order_id: nil,
      winning_consumer: nil,
      winners_shipping_address: nil,
      threshold_reached: false,
      )

    Deal.create(
      id: 114,
      name: "iPhone 6g",
      description: "iPhone 6",
      price: 10,
      image: nil,
      threshold: 2,
      start_date: nil,
      end_date: nil,
      status: "ready",
      supplier_id: 1,
      created_at: "2015-08-10 20:00:00",
      updated_at: "2015-08-10 21:00:00",
      url: "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQdRq0PxGe1HYR5kcCGZpKGIzGHw5mjBFTJZFLlqeZOobbqNlLvPg",
      product_type: "Electronics",
      winning_order_id: nil,
      winning_consumer: nil,
      winners_shipping_address: nil,
      threshold_reached: false,
      )

    Deal.create(
      id: 115,
      name: "XBOX ONEg",
      description: "XBOX ONE",
      price: 10,
      image: nil,
      threshold: 2,
      start_date: nil,
      end_date: nil,
      status: "ready",
      supplier_id: 1,
      created_at: "2015-08-10 20:00:00",
      updated_at: "2015-08-10 21:00:00",
      url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTwp4BVJdeXqJsdYFF7YPOhgLBOvET2x16-gxdIsMoDJ1-el2of9A",
      product_type: "Video Games",
      winning_order_id: nil,
      winning_consumer: nil,
      winners_shipping_address: nil,
      threshold_reached: false,
      )
